### ISSUE TITLE
Breast Cancer Prediction

### ISSUE THREAD

**Issue by sreevidya-16** [Recode-Hive/machine-learning-repos#113]
I want to develop ML model, that detects the Breast cancer.
@sanjay-kv  Please assign me this issue.

I am participating in GSSOC'24

**Comment by Shouryabhardwajj** [comment]
I am interested in this issue. Please assign me this

**Comment by Amishachoudhary22** [comment]
I am Interested in working on this issue. Please assign it to me.I am a GSSoC contributor

**Comment by SayantikaLaskar** [comment]
I would like to work on this issue kindly assign me this issue
