### ISSUE TITLE
DNA Classification

### ISSUE THREAD

**Issue by sreevidya-16** [Recode-Hive/machine-learning-repos#114]
I want to create a DNA Classification model, that determines if an unlabeled DNA sequence belongs to an existing class. 
It's a crucial challenge in computational biomedical data analysis and an important operation in genomic research.

Please assign this to me 

I am participating in GSSOC'24

**Comment by Shouryabhardwajj** [comment]
I am interested in this issue. Please assign me this

**Comment by sreevidya-16** [comment]
@sanjay-kv could you please look into this issue and assign this to me under GSSOC'24
