### ISSUE TITLE
diabetes prediction (Machine Learning Algorithms)

### ISSUE THREAD

**Issue by ranamanish674zu** [Recode-Hive/machine-learning-repos#118]
Can you assign it to me? @sanjay-kv 

Full name: Manish Rana
GitHub profile link: https://github.com/ranamanish674zu
Email ID: manish.rana2021@vitbhopal.ac.inn
Approach for this project: Will use ML algorithm and python
What is your participant role?: GSSoC-2024 contributor

Can you add the label for GSSoC, i want to work on it
Thanks.

**Comment by jahnavikandulapati** [comment]
I am interested in working on this project I am a contributor from GSSoC 2024.

**Comment by Amishachoudhary22** [comment]
I am interested in working on this issue.I am a contributor in GSSoC 2024

**Comment by aasthameh** [comment]
I am interested in working on this issue.

**Comment by sanjay-kv** [comment]
@aasthameh Its already assigned to a person, feel free to create a new one.
