### ISSUE TITLE
Movie Recommendation System

### ISSUE THREAD

**Issue by manikumarreddyu** [Recode-Hive/machine-learning-repos#165]
here in this movie recommendation system IMDB daataset is used
and also IMDB API is used for getting imagees while searching for movies
it recommends based on type of movie , based on similarity and movie ratings .

**Comment by manikumarreddyu** [comment]
:p assign me this task under GSSOC'24

**Comment by sanjay-kv** [comment]
cant assign more issues as its limited to 60 points
