### ISSUE TITLE
Regression-Analysis-of-COVID-19 

### ISSUE THREAD

**Issue by manikumarreddyu** [Recode-Hive/machine-learning-repos#167]
In this model Short term predictions were performed in order to study the impact and spread of the COVID-19 in coming days.

The following regression methods are used in building this model:

        Linear regression
        Polynomial Regression
        Ridge regression
        Polynomial Ridge regression
        SVM
        Decision tree

please assign me this task under GSSOC"24

**Comment by sanjay-kv** [comment]
cant assign more issues as its limited to 60 points
