### ISSUE TITLE
PDF-Chatbot-using-Langchain

### ISSUE THREAD

**Issue by manikumarreddyu** [Recode-Hive/machine-learning-repos#168]
In this project i have utilized  the power of OpenAI's language model and Langchain to enable users to interactively chat and extract information from multiple PDF documents.
The goal is to make it easier for users to get quick insights from various PDF files without the need to read each document manually.

The Chat with PDFs project is built on top of two powerful technologies: 
      OpenAI and Langchain.

:p assign me this task under GSSOC'24

**Comment by sanjay-kv** [comment]
cant assign more issues as its limited to 60 points
