### ISSUE TITLE
Hand Digit Recognition Using Convolutional Neural Network(CNN):

### ISSUE THREAD

**Issue by Anshika14528** [Recode-Hive/machine-learning-repos#2]
Handwritten digit recognition involves classifying images of handwritten digits (0-9) into their respective categories. CNNs are particularly well-suited for this task due to their ability to automatically and adaptively learn spatial hierarchies of features through backpropagation by using multiple building blocks, such as convolution layers, pooling layers, and fully connected layers.

 I agree to follow this project's Code of Conduct
 I'm a GSSoC'24 contributor
 I want to work on this issue

**Comment by sanjay-kv** [comment]
Make sure you create seperate folder and add the same

**Comment by lassmara** [comment]
Please assign me this issue.

**Comment by itssiddhantjain** [comment]
Hello @sanjay-kv , please assign this issue to me as I have already worked on this kind of problem in the past.
