### ISSUE TITLE
Updating README.md file

### ISSUE THREAD

**Issue by Harshitmishra001** [Recode-Hive/machine-learning-repos#205]
Hi!
Iwould Like to add the following to the Repo's readme.md file 😄
1.Adding Contibution Wall
2. Adding Animated Emojis
3. Adding Back to Top button at end of Readme to go to back top

**Comment by sanjay-kv** [comment]
Could you add more details and more look like ML capsule repo .. its available in gssoc project section

**Comment by Harshitmishra001** [comment]
Sure i will try to add it
