### ISSUE TITLE
Movie Genre Classification Prediction 

### ISSUE THREAD

**Issue by Manav173** [Recode-Hive/machine-learning-repos#217]
Overview:
This project aims to develop a predictive model for movie genre classification based on various features such as plot summary, cast, crew, and user reviews. This issue tracks the progress and tasks associated with the development of this predictive model.

Objective:
The primary objective of this project is to create a machine learning model that can accurately classify the genre of a movie based on its relevant attributes.

I would like this issue to be assigned to me as part of GSSoC'24. Thank you @sanjay-kv .

**Comment by Ar7109** [comment]
@sanjay-kv Please assign this issue to me under GSSOC

**Comment by Manav173** [comment]
I would like this issue to be assigned to me as part of GSSoC'24. Thank you @sanjay-kv .

**Comment by Akanksha4554** [comment]
@sanjay-kv Please assign this issue to me under GSSoc'24.

**Comment by sonali9564** [comment]
@sanjay-kv
Please assign this issue to me under GSSoC'24.

**Comment by Chaitanya110703** [comment]
Please can you assign this issue to me under GSSoC'24.

**Comment by Manav173** [comment]
As it is already added in the repo so closing this issue.
