### ISSUE TITLE
Cricket Player Analysis

### ISSUE THREAD

**Issue by aditya-bhaumik** [Recode-Hive/machine-learning-repos#225]
Objective

This project aims to analyze cricket player performance data using k-means clustering to identify patterns and group similar players. The project involves data preparation, feature selection (e.g., runs, batting average, strike rate, centuries, fifties), and determining the optimal number of clusters using the elbow method. The analysis will include visualizations like scatter plots and pair plots to represent clusters and key findings

**Comment by Samrudhi00** [comment]
Please assign this issue to me GSSOC 2024 Contributor.

**Comment by sonali9564** [comment]
@sanjay-kv
Please assign this issue to me under GSSoC'24.

**Comment by Akanksha4554** [comment]
@sanjay-kv Please assign this issue to me under GSSoc'24.

**Comment by aditya-bhaumik** [comment]
@sonali9564 @Akanksha4554 I have already been assigned this issue and i am working on it
