### ISSUE TITLE
Feat: Thyroid Cancer Recurrence Classification Model

### ISSUE THREAD

**Issue by arpy8** [Recode-Hive/machine-learning-repos#284]
I want to add a Thyroid Cancer Recurrence Classification Model. The model will be trained on the following dataset:
https://www.kaggle.com/datasets/jainaru/thyroid-disease-data/data

**Comment by Prachi194agrawal** [comment]
@arpy8 assign this issue to me

**Comment by AnjuMau8418** [comment]
I want to work on this issue. Please assign it to me.
