### ISSUE TITLE
💡[Feature]: leaf prediction

### ISSUE THREAD

**Issue by sunnyshin8** [Recode-Hive/machine-learning-repos#334]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

to detect leaf is it poisonous or not

### Use Case

herbal advantage

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by sunnyshin8** [comment]
I didn't receive score?pls help me out

**Comment by sanjay-kv** [comment]
what you mean, i assigned labels, it will take 12 hours leaderoar dto update daily
