### ISSUE TITLE
Predicting Student Dropout Rates Using Machine Learning Models

### ISSUE THREAD

**Issue by vivekvardhan2810** [Recode-Hive/machine-learning-repos#338]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I will predict the student Dropout rates using Logistic Regression, K-Nearest Neighbors (KNN) and K- Means Clustering.

### Use Case

Academic and Socio-Economic Factor

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [x] I want to work on this issue

**Comment by vivekvardhan2810** [comment]
@sanjay-kv, Sir i didn't get assigned yet, still go the labels added

**Comment by adityasingh-0803** [comment]
@sanjay-kv I can work on this
