### ISSUE TITLE
💡[Feature]: Stock  Turnover Ratio Dataset Analysis

### ISSUE THREAD

**Issue by ranamanish674zu** [Recode-Hive/machine-learning-repos#381]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

This information comes from the Federal Reserve Bank of St. Louis. The dataset contains data about the total value of shares traded during certain time periods versus the average market capitalization for that period.
https://fred.stlouisfed.org/series/DDEM01USA156NWDB

### Use Case

we can analyze the turnover of the stock which will be very helpful to understand the market condition then according to the condition we can take the actions like to increase or decrease the production or how to to marketing 

### Benefits

it will help to run the business smoothly

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by ranamanish674zu** [comment]
Can you assign it to me? @sanjay-kv

Full name: Manish Rana
GitHub profile link: https://github.com/ranamanish674zu
Email ID: [manish.rana2021@vitbhopal.ac.in](mailto:manish.rana2021@vitbhopal.ac.in)
What is your participant role?: GSSoC-2024 contributor

Can you add the label for GSSoC, i want to work on it
Thanks.

**Comment by malvika-sinha** [comment]
I wish to work on this. kindly assign this task to me.

**Comment by sanjay-kv** [comment]
I can see @malvika-sinha most of the issues are assigned, feel free to create a new issue and work on the same.
