### ISSUE TITLE
💡[Feature]:  Home income prediction using random forest and XGboost

### ISSUE THREAD

**Issue by RajKhanke** [Recode-Hive/machine-learning-repos#389]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

this system based on machine learning will predict the household income from various input factors like occupation, dependencies ,marital status, dependents , education , employment, work experience, wealth and property status , assets and other relevant primary information using machine learning models like random forest and XgBoost.

The csv dataset of home income prediction available on Kaggle can be used for this purpose

### Use Case

this project will help to find out estimated income of a family based on various inputs

### Benefits

The following benefits the project offers :
1) find out the pattern or factors affecting family income
2)predict the estimated family income using robust machine learning model
3)help in analyzing and observing dataset on family income available on kaggle

### Add ScreenShots

none

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Kirti-Pant** [comment]
@sanjay-kv  I can work on this is please assign this issue to me??

**Comment by sanjay-kv** [comment]
Hi @Kirti-Pant , as you can see most of the issues are already assigned

![image](https://github.com/Recode-Hive/machine-learning-repos/assets/30715153/da5e723d-b260-40da-b78e-416a202f48ac)
