### ISSUE TITLE
💡[Feature]: Hypothesis Testing Techniques

### ISSUE THREAD

**Issue by ranamanish674zu** [Recode-Hive/machine-learning-repos#411]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Hypothesis testing involves making decisions about a population based on sample data. Here are some common types of hypothesis testing methods and approaches:
1. Z-Test
 2. T-Test
 3.  ANOVA (Analysis of Variance)
 4. Chi-Square Test
 5.  Mann-Whitney U Test
 6. Wilcoxon Signed-Rank Test
 7. Kruskal-Wallis Test
 8. F-Test
 9. Correlation Tests
 10. Regression Analysis

### Use Case

Hypothesis testing is employed to make inferences about a population based on sample data, providing a formal process for testing assumptions and theories. It is used extensively in scientific research to validate experimental results and in various fields such as psychology, medicine, and economics to test hypotheses about population parameters. In business, hypothesis testing can be used to determine if changes in processes, marketing strategies, or product designs have statistically significant effects. Additionally, it is a critical tool in quality control and manufacturing to ensure that products meet predefined standards and specifications. By evaluating the evidence provided by sample data, hypothesis testing helps in making informed decisions and understanding the underlying mechanisms of observed phenomena.

### Benefits

The benefits of hypothesis testing include providing a structured approach to decision-making, reducing reliance on intuition and subjective judgment. It ensures objective evaluation of data, helping to validate or refute claims and theories with statistical rigor. This method is crucial in quality control, as it helps identify whether variations in products are due to random chance or specific causes, leading to improved standards and consistency. In policy-making, hypothesis testing offers a scientific basis for evaluating the effectiveness of programs and interventions. It also aids businesses in optimizing strategies by identifying significant differences and effects, ultimately contributing to better outcomes and innovations. Overall, hypothesis testing enhances the reliability and validity of conclusions drawn from data.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Kirti-Pant** [comment]
@sanjay-kv  can you assign this issue to me?
