### ISSUE TITLE
💡[Feature]:  Domestic Violence against Women Classification

### ISSUE THREAD

**Issue by AmrutaJayanti** [Recode-Hive/machine-learning-repos#475]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I would like to train a model which classifies the violence against women in rural areas using a dataset from kaggle. The dataset includes the features such as  Age ,Education ,Marital status , Employment etc.

### Use Case

To analyse correlation between various socio-economic factors and domestic violence.

### Benefits

N/A

### Add ScreenShots

N/A

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by AmrutaJayanti** [comment]
@sanjay-kv You havent assigned this issue . Please assign me .

**Comment by sanjay-kv** [comment]
Thanks for highlighting i missed it.
