### ISSUE TITLE
Word Embeddings Generation System Using Pytorch only

### ISSUE THREAD

**Issue by ubaid2751** [Recode-Hive/machine-learning-repos#478]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Implement a word embedding generation system using Pytorch only. This feature should allow users to generate word embeddings from a corpus of text and save them in a format that can be easily integrated into various machine-learning models.

### Use Case

This feature would enhance the project by allowing users to generate high-quality word embeddings for natural language processing tasks. Word embeddings are crucial for capturing semantic relationships between words, which can improve the performance of text-based models

### Benefits

Improved Text Processing: Better word embeddings improve model performance in NLP tasks such as text classification, sentiment analysis, and named entity recognition.
Flexibility: Users can generate embeddings tailored to their specific datasets and use cases.
Ease of Use: Simplifies the process of generating and using word embeddings, making it more accessible to users with varying levels of expertise.

### Add ScreenShots

N/A

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by ubaid2751** [comment]
@sanjay-kv Is it assigned?

**Comment by sanjay-kv** [comment]
thanks for reminding. i forgot
