### ISSUE TITLE
Cricket Shots Detection Using Deep Learning

### ISSUE THREAD

**Issue by vivekvardhan2810** [Recode-Hive/machine-learning-repos#49]
I would like to add a Cricket Shots Detection  model using DL.

I agree to follow this project's Code of Conduct
I'm a GSSoC'24 contributor
I want to work on this issue

Please assign this issue @sanjay-kv

**Comment by aryanchauh** [comment]
I have done two or three CNN project. 
Can u please assign me this issue @sanjay-kv

**Comment by vivekvardhan2810** [comment]
I had kept this issue before you 
Pls assign me this @sanjay-kv

**Comment by vivekvardhan2810** [comment]
Sir @sanjay-kv, Can you close this Issue as you have Merged MY PR
