### ISSUE TITLE
Types of Machine Learning:

### ISSUE THREAD

**Issue by Anshika14528** [Recode-Hive/machine-learning-repos#52]
Explaining about different types of machine learning:
1. Supervised Machine Learning
2. Unsupervised Machine Learning
3. Semi-Supervised Machine Learning
4. Reinforcement Learning

I agree to follow this project's Code of Conduct
I'm a GSSoC'24 contributor
I want to work on this issue

**Comment by TanishaVerma-08** [comment]
Hello there, I am a GSSoc'24 contributor and also I am a Machine learning student. I would like to contribute on the topic of types of machine learning. 
Kindly assign me the issue.
