### ISSUE TITLE
Activation Functions add graph under gssoc

### ISSUE THREAD

**Issue by kabeer09** [Recode-Hive/machine-learning-repos#523]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

add graph in Activation Functions

### Suggested Change

add graph where user understand the activation funtions better

### Rationale

graph is important in Activation Functions how to funtion vary

### Urgency

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by kabeer09** [comment]
u assign this issue to me to add graph in the repo

**Comment by kabeer09** [comment]
add more details regarding activation functions under gssoc

**Comment by kabeer09** [comment]
please check i update sucessfully or not
https://github.com/Recode-Hive/machine-learning-repos/commit/88cd8dd9d005275c7fc9d028fc9ccda28388bc7b

**Comment by kabeer09** [comment]
Activation_and_Loss_function

**Comment by kabeer09** [comment]
Sir...please check I contribute successfully

**Comment by sanjay-kv** [comment]
you did

**Comment by kabeer09** [comment]
yes you check 

https://github.com/Recode-Hive/machine-learning-repos/tree/88cd8dd9d005275c7fc9d028fc9ccda28388bc7b/Activation_and_Loss_function

**Comment by kabeer09** [comment]
sir how i check my repo is contribute in gssoc or not

**Comment by sanjay-kv** [comment]
![image](https://github.com/Recode-Hive/machine-learning-repos/assets/30715153/9333cd68-ed77-4353-8d5d-9facf6f7d7ad)
https://www.youtube.com/watch?v=Y9PYaPZgikg&t=1s watch this video

**Comment by kabeer09** [comment]
sir check this issue i solve or not

**Comment by kabeer09** [comment]
this contribute or not
