### ISSUE TITLE
add readme file Airlines Delay Prediction under gssoc

### ISSUE THREAD

**Issue by kabeer09** [Recode-Hive/machine-learning-repos#538]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

add file

### Suggested Change

add readme file

### Urgency

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by kabeer09** [comment]
issue solve #545

**Comment by kabeer09** [comment]
please sir check contribute or not

**Comment by sanjay-kv** [comment]
yes
