### ISSUE TITLE
💡[Feature]: Loan Status Prediction 

### ISSUE THREAD

**Issue by PradnyaGaitonde** [Recode-Hive/machine-learning-repos#546]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Develop a machine learning model that predicts the status of a loan application (approved, rejected, defaulted) based on various borrower and loan characteristics. 

### Use Case

This predictive model will help financial institutions make informed decisions, reduce default rates, and improve profitability.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Shantnu-singh** [comment]
hey @PradnyaGaitonde. I also have experience in this these type of problem and would be happy to help out on this project.
