### ISSUE TITLE
📝[Docs]: Adding a new documentation : An Introduction to Supervised and Unsupervised Learning

### ISSUE THREAD

**Issue by Parth-2701** [Recode-Hive/machine-learning-repos#567]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

By adding a new documentation , the  readers will be able  to strengthen their basics of Machine Learning. Planned to have references from the Machine Learning Specialization course , it will certainly help the users to not go haywire when they just want an introduction to M.L. 

### Suggested Change

Adding a new md file will save time of the users.

### Rationale

This will be beneficial for newcomers.

### Urgency

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by sanjay-kv** [comment]
No documenttion for existing projects is needed right now.
