### ISSUE TITLE
update readme.md file under gssoc

### ISSUE THREAD

**Issue by kabeer09** [Recode-Hive/machine-learning-repos#570]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

issue in AI_CHATBOT update the readme file 

### Suggested Change

update

### Urgency

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by sanjay-kv** [comment]
no this is not required at the moment
