### ISSUE TITLE
💡[Feature]: Graph Neural Networks (GNNs)

### ISSUE THREAD

**Issue by ranamanish674zu** [Recode-Hive/machine-learning-repos#631]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Modeling and analyzing data with a graph structure.
Techniques: Graph Convolutional Networks (GCN), Graph Attention Networks (GAT).

### Use Case

i will help us to optimize the learning power , will help us find the network between the nodes using graph , as we know the graph is most popular network  & anywhere the graph is used so with the help of graph in learning we can optimize our learning power .

### Benefits

can help to manage different type of networks.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by sanjay-kv** [comment]
@ranamanish674zu Just a friendly reminder , there is a limitation on this repo

**Comment by ranamanish674zu** [comment]
> @ranamanish674zu Just a friendly reminder , there is a limitation on this repo

@sanjay-kv okay sir
