### ISSUE TITLE
Feature - Machine learning Basics

### ISSUE THREAD

**Issue by Abhay182005dat** [Recode-Hive/machine-learning-repos#67]
Greetings !!

I thought if this is a ML repository then ofcourse beginners like me would also like to learn some basics about Datascience to learn ML right.So I would like to make a small notebook on learning matplotlib pyplot and its properties. :)

I guess that would be useful for many people.

Thank You

**Comment by akashlogics** [comment]
Hi Sir, I just messaged you in Discord that you will assign me this project. Can you please assign this so that I can do my first PR to this issue? And please label it as GSOC 24.

**Comment by Abhay182005dat** [comment]
> Hi Sir, I just messaged you in Discord that you will assign me this project. Can you please assign this so that I can do my first PR to this issue? And please label it as GSOC 24.

Please make a new issue and ask sir about the modification you want to make .It will be beneficial for you . 
:)

**Comment by sanjay-kv** [comment]
Hi, i got busy with leaderboard launch, assigned this issue to you

**Comment by Abhay182005dat** [comment]
> Hi, i got busy with leaderboard launch, assigned this issue to you
Its Ohk sir...

Sir I don't know if its good or not to ask you about this but i think that this issue deserves a level 2 or level 3 as it will be included with all the basics of matplotlib in the notebook.

Regards :)
