### ISSUE TITLE
Adding Plant Disease Prediction Using Tensorflow 

### ISSUE THREAD

**Issue by its-kumar-yash** [Recode-Hive/machine-learning-repos#73]
Overview:
Aim is to develop a predictive model for Plant disease using TensorFlow.

Objective:
The primary objective of this project is to create a machine-learning model that can accurately predict the disease by analyzing Plant's leaf Image.

I would like this issue to be assigned to me as part of GSSoC'24. Thank you.

**Comment by akashlogics** [comment]
I would like to work on this issue as I have learned many basics of tensor flow and small projects. So can you assign me do this work on this issue?
and label it as Gssoc 24

**Comment by sanjay-kv** [comment]
Hi, i got busy with leaderboard launch, assigned this issue to you

**Comment by its-kumar-yash** [comment]
> Hi, i got busy with leaderboard launch, assigned this issue to you

No problem 👍
