### ISSUE TITLE
enhancement of readme.md in support vector machine module

### ISSUE THREAD

**Issue by jahnvisahni31** [Recode-Hive/machine-learning-repos#75]
small update in readme.md required, I can add some animated emojis in the file , That will look good .

I agree to follow this project's Code of Conduct
I'm a GSSoC'24 contributor
I want to work on this issue

**Comment by sanjay-kv** [comment]
Hi, i got busy with leaderboard launch, assigned this issue to you

**Comment by jahnvisahni31** [comment]
no worries i can do this work by tomorrow

**Comment by jahnvisahni31** [comment]
i done this and make a pull request by name update readme.md please check

**Comment by jahnvisahni31** [comment]
please check i have done @sanjay-kv
