### ISSUE TITLE
Add MNIST Handwritten digits classifier using PyTorch

### ISSUE THREAD

**Issue by shrehs** [Recode-Hive/machine-learning-repos#93]
Hello!
Hope this finds you well. I think it would be great to add an project under Computer Vision to this repository.
If not handwritten digits classifier, it would be great to add MNIST fashion classifier.  Please do consider this.

Thank you!

**Comment by shrehs** [comment]
Please do assign this issue to me under GSSOC'24.
Thank you again!

**Comment by sanjay-kv** [comment]
Hi, i got busy with leaderboard launch, assigned this issue to you

**Comment by shrehs** [comment]
No issues. Thank you for assigning the Issue.
